from __future__ import annotations

from typing import Any, Generic, TypeVar

from sqlalchemy import or_
from sqlalchemy.orm import Session

from src.app.core.constants import SortOrder
from src.app.utils.pagination import PaginationInfo, build_pagination

ModelType = TypeVar("ModelType")
IdType = TypeVar("IdType")


class BaseRepository(Generic[ModelType, IdType]):
    model: type[ModelType]
    search_fields: list[str] = []

    def __init__(self, db: Session):
        """
        Initialize the repository with the given SQLAlchemy session.

        Args:
            db (Session): The SQLAlchemy session to use for database operations.
        """
        self.db = db

    def create(self, entity: ModelType) -> ModelType:
        """
        Add a new entity to the database and persist it.

        Args:
            entity (ModelType): The entity to be added.

        Returns:
            ModelType: The persisted entity with any updated fields (e.g., autogenerated IDs).
        """
        self.db.add(entity)
        self.db.commit()
        self.db.refresh(entity)
        return entity

    def get_by_id(self, entity_id: IdType) -> ModelType | None:
        """
        Retrieve an entity by its unique identifier.

        Args:
            entity_id (IdType): The ID of the entity to retrieve.

        Returns:
            ModelType | None: The entity if found, otherwise None.
        """
        return (
            self.db.query(self.model).filter(self.model.id == entity_id).one_or_none()
        )

    def list(
        self,
        limit: int | None = None,
        offset: int | None = None,
        *,
        order_by: SortOrder | None = None,
        options: list[Any] | None = None,
        search: str | None = None,
    ) -> tuple[PaginationInfo, list[ModelType]]:
        """
        Retrieve paginated results plus pagination metadata.

        Returns:
            tuple[PaginationInfo, list[ModelType]]: (pagination, items)
        """

        query = self._build_base_query(options)
        query = self._apply_search(query, search)
        query = self._apply_sorting(query, order_by)

        offset, limit = self._normalize_pagination(offset, limit)

        total = query.count()

        query = self._apply_pagination(query, offset, limit)
        items = query.all()

        pagination = build_pagination(
            total=total,
            limit=limit if limit is not None else total,
            offset=offset,
        )

        return pagination, items

    def _apply_search(self, query, search: str | None):
        """
        Apply search filtering to the SQLAlchemy query based on the provided search string.

        Args:
            query: SQLAlchemy query object to filter.
            search (str | None): The search term to look for in designated search fields.

        Returns:
            The filtered query if a search term is supplied and searchable fields exist
            otherwise, the original query.
        """

        if not search or not self.search_fields:
            return query

        conditions = [
            getattr(self.model, field).ilike(f"%{search}%")
            for field in self.search_fields
            if hasattr(self.model, field)
        ]

        if conditions:
            query = query.filter(or_(*conditions))

        return query

    def partial_update(self, entity: ModelType) -> ModelType:
        """
        Persist changes made to an existing entity.

        Args:
            entity (ModelType): The entity with updated fields.

        Returns:
            ModelType: The updated entity instance.
        """
        self.db.commit()
        self.db.refresh(entity)
        return entity

    def delete(self, entity: ModelType) -> None:
        """
        Remove an entity from the database.

        Args:
            entity (ModelType): The entity to be deleted.
        """
        self.db.delete(entity)
        self.db.commit()

    def _build_base_query(self, options: list[Any] | None):
        """
        Construct the base SQLAlchemy query for the repository model.

        Applies loading options if provided (e.g., eager loading relationships).

        Args:
            options (list[Any] | None): Optional SQLAlchemy loader options.

        Returns:
            Query: The base SQLAlchemy query object for the model.
        """
        query = self.db.query(self.model)

        if options:
            query = query.options(*options)

        return query

    def _apply_sorting(self, query, order_by: SortOrder | None):
        """
        Apply sorting to the given SQLAlchemy query based on the provided order_by parameter.

        Uses the model's "created_at" column to sort by newest or oldest order.
        If no order_by is provided or if the model lacks a "created_at" attribute,
        the query is returned unmodified.

        Args:
            query: The SQLAlchemy query object to modify.
            order_by (SortOrder | None): The sorting direction,
            typically SortOrder.NEWEST or SortOrder.OLDEST.

        Returns:
            The SQLAlchemy query object with ordering applied if applicable.
        """
        if not order_by or not hasattr(self.model, "created_at"):
            return query

        created_at_col = getattr(self.model, "created_at")

        return query.order_by(
            created_at_col.desc()
            if order_by == SortOrder.NEWEST
            else created_at_col.asc()
        )

    def _normalize_pagination(
        self,
        offset: int | None,
        limit: int | None,
    ) -> tuple[int, int | None]:
        """
        Normalize and validate pagination parameters for query offset and limit.

        Ensures that offset is a non-negative integer and
        that limit is either a non-negative integer or None.
        Converts None or invalid (negative) values to safe defaults.

        Args:
            offset (int | None): The offset value to normalize.
            Defaults to 0 if None or less than 0.
            limit (int | None): The limit value to normalize.
            Stays None if None, otherwise ensured non-negative.

        Returns:
            tuple[int, int | None]: Tuple of normalized (offset, limit).
        """
        offset = max(offset or 0, 0)
        limit = None if limit is None else max(limit, 0)

        return offset, limit

    def _apply_pagination(self, query, offset: int, limit: int | None):
        """
        Apply pagination to the given SQLAlchemy query.

        Offsets the result set and limits the number of rows returned, if a limit is specified.

        Args:
            query: The SQLAlchemy query object to modify.
            offset (int): The number of rows to skip before returning results.
            limit (int | None): The maximum number of rows to return. If None, no limit is applied.

        Returns:
            The SQLAlchemy query object with offset and limit applied.
        """
        if limit is not None:
            query = query.limit(limit)

        return query.offset(offset)
