from __future__ import annotations

from typing import Any, Generic, TypeVar

from sqlalchemy.orm import Session

from app.utils.pagination import PaginationInfo, build_pagination

ModelType = TypeVar("ModelType")
IdType = TypeVar("IdType")


class BaseRepository(Generic[ModelType, IdType]):
    model: type[ModelType]

    def __init__(self, db: Session):
        """
        Initialize the repository with the given SQLAlchemy session.

        Args:
            db (Session): The SQLAlchemy session to use for database operations.
        """
        self.db = db

    def create(self, entity: ModelType) -> ModelType:
        """
        Add a new entity to the database and persist it.

        Args:
            entity (ModelType): The entity to be added.

        Returns:
            ModelType: The persisted entity with any updated fields (e.g., autogenerated IDs).
        """
        self.db.add(entity)
        self.db.commit()
        self.db.refresh(entity)
        return entity

    def get_by_id(self, entity_id: IdType) -> ModelType | None:
        """
        Retrieve an entity by its unique identifier.

        Args:
            entity_id (IdType): The ID of the entity to retrieve.

        Returns:
            ModelType | None: The entity if found, otherwise None.
        """
        return (
            self.db.query(self.model).filter(self.model.id == entity_id).one_or_none()
        )

    def list(
        self,
        limit: int,
        offset: int,
        *,
        order_by: Any = None,
        options: list[Any] | None = None,
    ) -> tuple[PaginationInfo, list[ModelType]]:
        """
        Retrieve paginated results plus pagination metadata.

        Returns:
            tuple[PaginationInfo, list[ModelType]]: (pagination, items)
        """
        base_query = self.db.query(self.model)
        total = base_query.count()

        page_query = self.db.query(self.model)
        if options:
            page_query = page_query.options(*options)
        if order_by is not None:
            page_query = page_query.order_by(order_by)

        items = page_query.limit(limit).offset(offset).all()

        pagination = build_pagination(total=total, limit=limit, offset=offset)
        return pagination, items

    def partial_update(self, entity: ModelType) -> ModelType:
        """
        Persist changes made to an existing entity.

        Args:
            entity (ModelType): The entity with updated fields.

        Returns:
            ModelType: The updated entity instance.
        """
        self.db.commit()
        self.db.refresh(entity)
        return entity

    def delete(self, entity: ModelType) -> None:
        """
        Remove an entity from the database.

        Args:
            entity (ModelType): The entity to be deleted.
        """
        self.db.delete(entity)
        self.db.commit()
