[project]
name = "fastapi-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.135.1",
    "python-jose[cryptography]>=3.3.0",
    "psycopg[binary]>=3.3.3",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.48",
    "pyngrok>=7.5.1",
    "svix>=1.88.0",
    "python-dotenv>=1.2.2",
    "tenacity>=9.1.4",
    "certifi>=2026.2.25",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.8",
    "ty>=0.0.27",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
line-length = 100
target-version = "py313"

select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "N",  # naming
  "I",  # import sort
  "UP", # pyupgrade
]

ignore = ["UP046"]

fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ty]
include = ["."]
exclude = [".venv", "migrations", "tests"]

strict = true
